name: Linter

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: HTML Lint
      uses: jakejarvis/html-validate-action@v2
      with:
        files: ./**/*.html
        config: .htmlvalidate.json

    - name: CSS Lint
      run: |
        npm install stylelint stylelint-config-standard
        npx stylelint '**/*.css'

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
